spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_crud?useSSL=false
    username: root
    password: root

  #Hibernate config
jpa:
  hibernate:
    ddl-auto: update   # options: none, validate, update, create, create-drop
  show-sql: true        # logs SQL queries in console
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      jdbc:
        time_zone: UTC
  application:
    name: demo
